name: Create release
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 24576
          swap-size-mb: 2048
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{secrets.GIT_PUSH_TOKEN}}
      - name: Create release commit
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y git-buildpackage
          export DEBEMAIL="dev@radxa.com"
          export DEBFULLNAME='"Radxa Computer Co., Ltd"'
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          make dch
      - name: Test
        run: |
          sudo apt-get build-dep --no-install-recommends -y .
          make all test deb
      - name: Push
        run: |
          git push
