name: Build & Release
on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      distro: ${{ steps.distro_check.outputs.distro }}
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 24576
          swap-size-mb: 2048
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: pre-commit check
        run: |
          pip install pre-commit
          if ! pre-commit run --all-files --show-diff-on-failure
          then
            echo ''
            echo '=== Code style issue detected! ==='
            echo 'Suggest changes are listed above.'
            echo 'Please install pre-commit and run `pre-commit run --all-files` to fix it.'
            echo 'Strongly recommended to run `pre-commit install` to catch issues before pushing.'
            echo 'You can learn more abour pre-commit from https://pre-commit.com/'
            exit 1
          fi
      - name: Test
        run: |
          make test
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get build-dep --no-install-recommends -y .
          make all deb
      - name: Workaround actions/upload-artifact#176
        run: |
          echo "artifacts_path=$(realpath ..)" >> $GITHUB_ENV
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ env.artifacts_path }}/*.deb
            src/packages/arm64/**/*.deb
      - name: Check if the latest version is releasable
        id: distro_check
        run: |
          version="$(dpkg-parsechangelog -S Version)"
          if [[ -n "$(git tag -l "$version")" ]]
          then
            echo "distro=UNRELEASED" >> "$GITHUB_OUTPUT"
          else
            echo "distro=$(dpkg-parsechangelog -S Distribution)" >> "$GITHUB_OUTPUT"
          fi
  release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' && needs.build.outputs.distro != 'UNRELEASED' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: .artifacts
      - name: Prepare for release
        run: |
          version="$(dpkg-parsechangelog -S Version)"
          echo "version=$version" >> $GITHUB_ENV
          echo "changes<<EOF" >> $GITHUB_ENV
          echo '```' >> $GITHUB_ENV
          echo "$(dpkg-parsechangelog -S Changes)" >> $GITHUB_ENV
          echo '```' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "$version" > VERSION
          make pkg.conf || true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.version }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: ${{ github.ref_name }}
          draft: false
          prerelease: true
          fail_on_unmatched_files: false
          files: |
            .artifacts/**/*.deb
            pkg.conf
            VERSION
      - name: Append changelog
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.version }}
          body: |
            ## Changelog for ${{ env.version }}
            ${{ env.changes }}
          append_body: true
      # - name: Update Test repos
      #   uses: radxa-repo/update-repo-action@main
      #   with:
      #     test-repo: true
      #     token: ${{ secrets.RADXA_APT_TEST_REPO_TOKEN }}
